name: eQuantic Core Data EntityFramework

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Build eQuantic.Core.Data.EntityFramework Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework/eQuantic.Core.Data.EntityFramework.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework .net 6 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework/eQuantic.Core.Data.EntityFramework.Net6.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework .net 7 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework/eQuantic.Core.Data.EntityFramework.Net7.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework .net 8 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework/eQuantic.Core.Data.EntityFramework.Net8.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework .net 9 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework/eQuantic.Core.Data.EntityFramework.Net9.csproj --configuration Release
      
      - name: Build eQuantic.Core.Data.EntityFramework.SqlServer Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.SqlServer/eQuantic.Core.Data.EntityFramework.SqlServer.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.SqlServer .net 6 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.SqlServer/eQuantic.Core.Data.EntityFramework.SqlServer.Net6.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.SqlServer .net 7 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.SqlServer/eQuantic.Core.Data.EntityFramework.SqlServer.Net7.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.SqlServer .net 8 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.SqlServer/eQuantic.Core.Data.EntityFramework.SqlServer.Net8.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.SqlServer .net 9 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.SqlServer/eQuantic.Core.Data.EntityFramework.SqlServer.Net9.csproj --configuration Release

      - name: Build eQuantic.Core.Data.EntityFramework.MySql Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.MySql/eQuantic.Core.Data.EntityFramework.MySql.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.MySql .net 8 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.MySql/eQuantic.Core.Data.EntityFramework.MySql.Net8.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.MySql .net 9 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.MySql/eQuantic.Core.Data.EntityFramework.MySql.Net9.csproj --configuration Release
        
      - name: Build eQuantic.Core.Data.EntityFramework.PostgreSql Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.PostgreSql/eQuantic.Core.Data.EntityFramework.PostgreSql.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.PostgreSql .net 8 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.PostgreSql/eQuantic.Core.Data.EntityFramework.PostgreSql.Net8.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.PostgreSql .net 9 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.PostgreSql/eQuantic.Core.Data.EntityFramework.PostgreSql.Net9.csproj --configuration Release
      
      - name: Build eQuantic.Core.Data.EntityFramework.MongoDb Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.MongoDb/eQuantic.Core.Data.EntityFramework.MongoDb.csproj --configuration Release
      - name: Build eQuantic.Core.Data.EntityFramework.MongoDb .net 9 Library
        run: dotnet build ./src/eQuantic.Core.Data.EntityFramework.MongoDb/eQuantic.Core.Data.EntityFramework.MongoDb.Net9.csproj --configuration Release
      
      - name: Push package into Nuget.org
        run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{secrets.nuget_key}} -s https://api.nuget.org/v3/index.json
